name: tagged-release

on:
  push:
    tags:
      - 'v*'

jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build app
        run: |
          yarn install --frozen-lockfile
          yarn build
          cp config.example.js build
          pushd build
          zip -qr "../TileBoard.zip" .

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            TileBoard.zip

      - name: Get version
        id: get-version
        run: |
          version=`echo $(jq -r '.version' package.json)`
          echo "::set-output name=version::${version}"

      - name: Bump TileBoard in addon
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: resoai
          repo: TileBoard-addon
          workflow_id: on_tileboard_release.yaml
          ref: main
          inputs: |
            version: ${{ steps.get-version.outputs.version }}
            release_url: https://github.com/resoai/TileBoard/releases/tag/v${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_WORKFLOW_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker build
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
            --pull \
            -t tileboard/tileboard:latest \
            -t tileboard/tileboard:${{ steps.get-version.outputs.version }} \
            -f docker/Dockerfile.run \
            --push \
            .
